/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import type {
  CreateSellerBody,
  CreateSellerResponse,
  SellerProfileResponse,
} from '.././model'

/**
 * @summary Create a new seller
 */
export const registerSellerControllerHandle = (
  createSellerBody: CreateSellerBody,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<CreateSellerResponse>> => {
  return axios.default.post(
    `http://localhost:3333/sellers`,
    createSellerBody,
    options
  )
}

export const getRegisterSellerControllerHandleMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerSellerControllerHandle>>,
    TError,
    { data: CreateSellerBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerSellerControllerHandle>>,
  TError,
  { data: CreateSellerBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerSellerControllerHandle>>,
    { data: CreateSellerBody }
  > = props => {
    const { data } = props ?? {}

    return registerSellerControllerHandle(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterSellerControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerSellerControllerHandle>>
>
export type RegisterSellerControllerHandleMutationBody = CreateSellerBody
export type RegisterSellerControllerHandleMutationError = AxiosError<void>

/**
 * @summary Create a new seller
 */
export const useRegisterSellerControllerHandle = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerSellerControllerHandle>>,
    TError,
    { data: CreateSellerBody },
    TContext
  >
  axios?: AxiosRequestConfig
}): UseMutationResult<
  Awaited<ReturnType<typeof registerSellerControllerHandle>>,
  TError,
  { data: CreateSellerBody },
  TContext
> => {
  const mutationOptions =
    getRegisterSellerControllerHandleMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * @summary Get the seller profile
 */
export const sellerProfileControllerHandle = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SellerProfileResponse>> => {
  return axios.default.get(`http://localhost:3333/sellers/me`, options)
}

export const getSellerProfileControllerHandleQueryKey = () => {
  return [`http://localhost:3333/sellers/me`] as const
}

export const getSellerProfileControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getSellerProfileControllerHandleQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof sellerProfileControllerHandle>>
  > = ({ signal }) => sellerProfileControllerHandle({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type SellerProfileControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof sellerProfileControllerHandle>>
>
export type SellerProfileControllerHandleQueryError = AxiosError<unknown>

export function useSellerProfileControllerHandle<
  TData = Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
  TError = AxiosError<unknown>,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
        TError,
        TData
      >,
      'initialData'
    >
  axios?: AxiosRequestConfig
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useSellerProfileControllerHandle<
  TData = Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
        TError,
        TData
      >,
      'initialData'
    >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useSellerProfileControllerHandle<
  TData = Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get the seller profile
 */

export function useSellerProfileControllerHandle<
  TData = Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof sellerProfileControllerHandle>>,
      TError,
      TData
    >
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getSellerProfileControllerHandleQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
