/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import * as axios from 'axios'
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios'
import type { AmountResponse, ViewsPerDayResponse } from '.././model'

/**
 * @summary Count the number of products sold by the seller in 30 days
 */
export const countSellerSoldProductsControllerHandle = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AmountResponse>> => {
  return axios.default.get('/sellers/metrics/products/sold', options)
}

export const getCountSellerSoldProductsControllerHandleQueryKey = () => {
  return ['/sellers/metrics/products/sold'] as const
}

export const getCountSellerSoldProductsControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getCountSellerSoldProductsControllerHandleQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>
  > = ({ signal }) =>
    countSellerSoldProductsControllerHandle({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type CountSellerSoldProductsControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>
>
export type CountSellerSoldProductsControllerHandleQueryError = AxiosError<void>

/**
 * @summary Count the number of products sold by the seller in 30 days
 */

export function useCountSellerSoldProductsControllerHandle<
  TData = Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerSoldProductsControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getCountSellerSoldProductsControllerHandleQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Count the amount of available products in 30 days.
 */
export const countSellerAvailableProductsControllerHandle = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AmountResponse>> => {
  return axios.default.get('/sellers/metrics/products/available', options)
}

export const getCountSellerAvailableProductsControllerHandleQueryKey = () => {
  return ['/sellers/metrics/products/available'] as const
}

export const getCountSellerAvailableProductsControllerHandleQueryOptions = <
  TData = Awaited<
    ReturnType<typeof countSellerAvailableProductsControllerHandle>
  >,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerAvailableProductsControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getCountSellerAvailableProductsControllerHandleQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof countSellerAvailableProductsControllerHandle>>
  > = ({ signal }) =>
    countSellerAvailableProductsControllerHandle({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof countSellerAvailableProductsControllerHandle>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type CountSellerAvailableProductsControllerHandleQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof countSellerAvailableProductsControllerHandle>>
  >
export type CountSellerAvailableProductsControllerHandleQueryError =
  AxiosError<void>

/**
 * @summary Count the amount of available products in 30 days.
 */

export function useCountSellerAvailableProductsControllerHandle<
  TData = Awaited<
    ReturnType<typeof countSellerAvailableProductsControllerHandle>
  >,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerAvailableProductsControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getCountSellerAvailableProductsControllerHandleQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Count the number of views received by the seller in 30 days
 */
export const countSellerViewsControllerHandle = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<AmountResponse>> => {
  return axios.default.get('/sellers/metrics/views', options)
}

export const getCountSellerViewsControllerHandleQueryKey = () => {
  return ['/sellers/metrics/views'] as const
}

export const getCountSellerViewsControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof countSellerViewsControllerHandle>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerViewsControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getCountSellerViewsControllerHandleQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof countSellerViewsControllerHandle>>
  > = ({ signal }) =>
    countSellerViewsControllerHandle({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof countSellerViewsControllerHandle>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type CountSellerViewsControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof countSellerViewsControllerHandle>>
>
export type CountSellerViewsControllerHandleQueryError = AxiosError<void>

/**
 * @summary Count the number of views received by the seller in 30 days
 */

export function useCountSellerViewsControllerHandle<
  TData = Awaited<ReturnType<typeof countSellerViewsControllerHandle>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerViewsControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getCountSellerViewsControllerHandleQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * @summary Count the number of views per day received by the seller in 30 days
 */
export const countSellerViewsPerDayControllerHandle = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<ViewsPerDayResponse>> => {
  return axios.default.get('/sellers/metrics/views/days', options)
}

export const getCountSellerViewsPerDayControllerHandleQueryKey = () => {
  return ['/sellers/metrics/views/days'] as const
}

export const getCountSellerViewsPerDayControllerHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getCountSellerViewsPerDayControllerHandleQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>
  > = ({ signal }) =>
    countSellerViewsPerDayControllerHandle({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type CountSellerViewsPerDayControllerHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>
>
export type CountSellerViewsPerDayControllerHandleQueryError = AxiosError<void>

/**
 * @summary Count the number of views per day received by the seller in 30 days
 */

export function useCountSellerViewsPerDayControllerHandle<
  TData = Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>,
  TError = AxiosError<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof countSellerViewsPerDayControllerHandle>>,
    TError,
    TData
  >
  axios?: AxiosRequestConfig
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getCountSellerViewsPerDayControllerHandleQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  query.queryKey = queryOptions.queryKey

  return query
}
